version: "3.7"
services:
  db:
    image: postgres:latest
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: fewo
      POSTGRES_USER: fewo
      DATABASE_HOST: 127.0.0.1
    ports:
      - "5432:5432"
volumes:
  db_data: